### ISSUE TITLE
Add contributor grid of profiles to bottom of README

### ISSUE THREAD

**Issue by pydanny** [pydanny/simplicity#14]

**Comment by nickatnight** [comment]
Claim this ticket @iwootten ! https://github.com/pydanny/simplicity/pull/17

Almost started working on this 😄

**Comment by iwootten** [comment]
Apologies @nickatnight - can't assign the ticket to myself.

Was done in #17

**Comment by pydanny** [comment]
Closed in your name. Wahoo!
